# This is a basic workflow to help you get started with Actions

name: CI-DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  GITHUB_RUN_ID: ${{secrets.GITHUB_RUN_ID}}
  GITHUB_RUN_NUMBER: ${{secrets.GITHUB_RUN_NUMBER}}

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.20.1


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs a single command using the runners shell
      - name: PWD
        run: pwd
      - name: Print working directory
        run: ls -alrt

      - name: npm build
        run: npm run build

      
      # Jira Keys
      - name: Parse Jira Keys from Commit
        id: jira_keys
        if: always()
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
          is-pull-request: ${{ github.event_name == 'pull_request' }}
          parse-all-commits: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Jira Deployment
      - name: Push Deployment Info to Jira
        if: steps.jira_keys.outputs.jira-keys != ''
        uses: rohit-gohri/jira-ci-cd-integration@v0
        with:
          state: ${{ env.BUILD_STATE }}
          environment: dev
          issue: "${{ steps.jira_keys.outputs.jira-keys }}"
          jira_instance: shlee-mz
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
          
      - name: Confirm Jira Build Output
        if: success()
        run: |
          echo ${{ steps.jira_keys.outputs.jira-keys }}
          echo "Jira Upload Build Info response: ${{ steps.push_build_info_to_jira.outputs.response }}"

