name: CI-DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  ARCHIVED_ARTIFACTS: quiz-app_build-artifacts.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: [Preparation] Checkout Source Control
        uses: actions/checkout@v3

      - name: [Preparation] Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.20.1

      - name: [Info] Check node version
        run: node -v

      - name: [Info] Print working directory
        run: ls -al

      - name: [Build] Install dependency packages
        run: yarn install

      - name: [Build] Build with yarn
        run: yarn run build

      - name: [Info] Print build directory
        run: ls -al build

      - name: [Package] Archive artifacts
        run: tar cfz $ARCHIVED_ARTIFACTS build

      - name: [Publish] Upload artifacts to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp $ARCHIVED_ARTIFACTS \
          --region ap-northeast-2 \
          s3://quiz-build-artifacts

      # Jira Keys
      - name: [Notification] Parse Jira Keys from Commit
        id: jira_keys
        if: always()
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
          is-pull-request: ${{ github.event_name == 'pull_request' }}
          parse-all-commits: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Jira Deployment
      - name: [Notification] Push Deployment Info to Jira
        if: steps.jira_keys.outputs.jira-keys != ''
        uses: rohit-gohri/jira-ci-cd-integration@v0
        with:
          state: ${{ env.BUILD_STATE }}
          environment: dev
          issue: "${{ steps.jira_keys.outputs.jira-keys }}"
          jira_instance: shlee-mz
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
          
